gitlab:
  url: http://gitlab.session1.techlunch.com:9980/
projects:
  exclude: tech-lunch/ci-cd-commands/.*
  order: ['name']
interval: 1
port: 3000
zoom: 0.7
columns: 2
header:
  title: 'Tech Lunch projects'
  subtitle: 'Pipelines monitor'
  image: 'https://www.thoughtworks.com/imgs/run_sustainable_business.png'